
try { site.core.main_BANG_(); } catch (e) { console.error("An error occurred when calling (site.core/main!)"); throw(e); }